### ISSUE TITLE
database - server behaviour with link containers

### ISSUE THREAD

**Issue by andirotter** [bestimmaa/docker-container-networking#2]
i experience in another project serious issues, when the linked container with the db crashed. turned out, the server relying on the db crashed too complete, but in a very strange way (setup was owncloud with maria db, each of them in a container). maybe you try it out with our setup ;-)

**Comment by bestimmaa** [comment]
We should look into this and maybe add some code to let the server crash intentionally. This might lead to some insights. These cases are way more interesting than the perfect hello world examples.
